"""empty message

Revision ID: 1e2e5bff5272
Revises: 
Create Date: 2020-03-01 11:37:48.120030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e2e5bff5272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('pw_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('food_category',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_kind',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nutrition_info', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packaging_kind',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packaging_state',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_item_state',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('food_item_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('packaging_kind_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('packaging_state_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('number_of_servings', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_kind.id'], ),
    sa.ForeignKeyConstraint(['packaging_kind_id'], ['packaging_kind.id'], ),
    sa.ForeignKeyConstraint(['packaging_state_id'], ['packaging_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_kind_category',
    sa.Column('food_kind_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('food_category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.ForeignKeyConstraint(['food_kind_id'], ['food_kind.id'], ),
    sa.PrimaryKeyConstraint('food_kind_id', 'food_category_id')
    )
    op.create_table('stock',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_item',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('stock_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('food_kind_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date_item_was_new', sa.DATE(), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['food_kind_id'], ['food_kind.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('stock_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_food_item_state',
    sa.Column('snapshot_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('food_item_state_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['food_item_state_id'], ['food_item_state.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'food_item_state_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_food_item_state')
    op.drop_table('snapshot')
    op.drop_table('food_item')
    op.drop_table('stock')
    op.drop_table('food_kind_category')
    op.drop_table('food_item_state')
    op.drop_table('packaging_state')
    op.drop_table('packaging_kind')
    op.drop_table('food_kind')
    op.drop_table('food_category')
    op.drop_table('app_user')
    # ### end Alembic commands ###
