"""empty message

Revision ID: 82ff4efd834a
Revises: 72177039a08b
Create Date: 2020-03-01 18:43:21.115874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ff4efd834a'
down_revision = '72177039a08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('food_item_state_food_item_id_fkey', 'food_item_state', type_='foreignkey')
    op.create_foreign_key(None, 'food_item_state', 'food_item', ['food_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_item_state', type_='foreignkey')
    op.create_foreign_key('food_item_state_food_item_id_fkey', 'food_item_state', 'food_kind', ['food_item_id'], ['id'])
    # ### end Alembic commands ###
