"""empty message

Revision ID: afe4a9cf7f5a
Revises: 697159f82a0a
Create Date: 2020-03-21 15:00:05.627124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe4a9cf7f5a'
down_revision = '697159f82a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'food_kind', 'unit_of_measurement', ['unit_of_measurement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_kind', type_='foreignkey')
    # ### end Alembic commands ###
