"""empty message

Revision ID: c9992a3ff353
Revises: 82ff4efd834a
Create Date: 2020-03-05 20:33:19.649830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9992a3ff353'
down_revision = '82ff4efd834a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_category', sa.Column('uniform_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'food_category', ['uniform_name'])
    op.add_column('food_kind', sa.Column('uniform_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'food_kind', ['uniform_name'])
    op.add_column('packaging_kind', sa.Column('uniform_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'packaging_kind', ['uniform_name'])
    op.add_column('packaging_state', sa.Column('uniform_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'packaging_state', ['uniform_name'])
    op.add_column('stock', sa.Column('uniform_name', sa.String(), nullable=False))
    op.drop_constraint('stock_name_key', 'stock', type_='unique')
    op.create_unique_constraint(None, 'stock', ['uniform_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    op.create_unique_constraint('stock_name_key', 'stock', ['name'])
    op.drop_column('stock', 'uniform_name')
    op.drop_constraint(None, 'packaging_state', type_='unique')
    op.drop_column('packaging_state', 'uniform_name')
    op.drop_constraint(None, 'packaging_kind', type_='unique')
    op.drop_column('packaging_kind', 'uniform_name')
    op.drop_constraint(None, 'food_kind', type_='unique')
    op.drop_column('food_kind', 'uniform_name')
    op.drop_constraint(None, 'food_category', type_='unique')
    op.drop_column('food_category', 'uniform_name')
    # ### end Alembic commands ###
