"""empty message

Revision ID: f22c492328cc
Revises: ffbeebca49b4
Create Date: 2020-03-07 12:12:09.587550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f22c492328cc'
down_revision = 'ffbeebca49b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_kind_nutrition_info',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('food_kind_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('calories_per_serving', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['food_kind_id'], ['food_kind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_kind_nutrition_info')
    # ### end Alembic commands ###
