"""empty message

Revision ID: f4a17aecd23a
Revises: c332ef6a2cf3
Create Date: 2020-03-29 15:18:29.241892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a17aecd23a'
down_revision = 'c332ef6a2cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_kind', sa.Column('serving_size', sa.Float(), nullable=True))
    op.drop_column('food_kind', 'units_to_serving_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_kind', sa.Column('units_to_serving_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('food_kind', 'serving_size')
    # ### end Alembic commands ###
