"""empty message

Revision ID: ffbeebca49b4
Revises: c9992a3ff353
Create Date: 2020-03-07 12:11:18.138503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffbeebca49b4'
down_revision = 'c9992a3ff353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_kind', 'notes')
    op.drop_column('food_kind', 'nutrition_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_kind', sa.Column('nutrition_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('food_kind', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
